[tool.poetry]
name = "tagger"
version = "0.1.0"
description = "Tags stuff"
authors = ["BodneyC <benjcarrington@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1"
PyYAML = "^6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-html = "^4.1.1"
pytest-cov = "^5.0.0"
codespell = "^2.2.6"
mypy = "^1.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib", "--tb=short"]
pythonpath = [".", "tagger", "tests"]

[tool.poetry.scripts]
tagger = "tagger.cli:main"
pytest = "pytest:main"

[tool.codespell]
# ignore-words-list = ""
# skip = ""
